# Generated by Django 5.2 on 2025-05-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('market', '0003_market_slug_alter_market_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='markets',
            field=models.ManyToManyField(blank=True, null=True, related_name='profiles', to='market.market'),
        ),
    ]
