# Generated by Django 5.2 on 2025-05-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='slug',
            field=models.SlugField(default='hello', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
